DROP TABLE IF EXISTS orders_products;
DROP TABLE IF EXISTS orders;
DROP SEQUENCE IF EXISTS orders_id_seq;
DROP TABLE IF EXISTS products;
DROP SEQUENCE IF EXISTS products_id_seq;

CREATE SEQUENCE products_id_seq AS INTEGER START WITH 1;
CREATE TABLE products (
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE products_id_seq PRIMARY KEY,
  name        LONGVARCHAR NOT NULL,
  price       NUMERIC(10,2),
  color       INTEGER,
  capacity    INTEGER,
  display     LONGVARCHAR,
  description LONGVARCHAR
);

CREATE SEQUENCE orders_id_seq AS INTEGER START WITH 1;
CREATE TABLE orders (
  id            INTEGER GENERATED BY DEFAULT AS SEQUENCE products_id_seq PRIMARY KEY,
  total_amount  NUMERIC(10,2) NOT NULL,
  name          LONGVARCHAR NOT NULL,
  email         LONGVARCHAR NOT NULL,
  phone         LONGVARCHAR,
  address       LONGVARCHAR NOT NULL
);

CREATE TABLE orders_products (
  order_id    INTEGER NOT NULL,
  product_id  INTEGER NOT NULL,
  FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);